"""empty message

Revision ID: 04346ee508d5
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 05:57:27.164277

"""
from alembic import op
import sqlalchemy as sa


revision = '04346ee508d5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

