"""empty message

Revision ID: 4a1b5117e979
Revises: 
Create Date: 2026-04-19 13:29:16.152960

"""
from alembic import op
import sqlalchemy as sa


revision = '4a1b5117e979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_accounts_username'), 'admin_accounts', ['username'], unique=True)
    op.create_table('contraindications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contraindications_name'), 'contraindications', ['name'], unique=True)
    op.create_table('custom_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('answer_type', sa.Enum('TEXT', 'NUMBER', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'BOOLEAN', name='custom_answer_type'), nullable=False),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_system = false) OR (key LIKE 'system:%')", name='ck_custom_question_system_key'),
    sa.CheckConstraint('"order" >= 0', name='ck_custom_question_order_positive'),
    sa.CheckConstraint('(min_value IS NULL) OR (max_value IS NULL) OR (min_value <= max_value)', name='ck_custom_question_value_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_question_active_order', 'custom_questions', ['is_active', 'order'], unique=False)
    op.create_index('idx_custom_question_system_active', 'custom_questions', ['is_system', 'is_active'], unique=False)
    op.create_index(op.f('ix_custom_questions_answer_type'), 'custom_questions', ['answer_type'], unique=False)
    op.create_index(op.f('ix_custom_questions_category'), 'custom_questions', ['category'], unique=False)
    op.create_index(op.f('ix_custom_questions_is_active'), 'custom_questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_custom_questions_is_system'), 'custom_questions', ['is_system'], unique=False)
    op.create_index(op.f('ix_custom_questions_key'), 'custom_questions', ['key'], unique=True)
    op.create_index(op.f('ix_custom_questions_order'), 'custom_questions', ['order'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_home_friendly', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('equipment', sa.String(length=64), nullable=True),
    sa.Column('is_cardio', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscles_name'), 'muscles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('tariff', sa.Enum('FREE', 'PREMIUM', name='tariff'), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_completed_profile', sa.Boolean(), nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_tdee', sa.Float(), nullable=True),
    sa.Column('cached_bmi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('custom_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_custom_question_option_sort_positive'),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'value', name='uq_question_option_value')
    )
    op.create_index(op.f('ix_custom_question_options_question_id'), 'custom_question_options', ['question_id'], unique=False)
    op.create_index(op.f('ix_custom_question_options_sort_order'), 'custom_question_options', ['sort_order'], unique=False)
    op.create_table('exercise_contraindications',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('contraindication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contraindication_id'], ['contraindications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'contraindication_id')
    )
    op.create_table('exercise_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'CANCELLED', name='trainingplanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date <= end_date', name='ck_training_plan_date_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_plan_user_status', 'training_plans', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_training_plans_end_date'), 'training_plans', ['end_date'], unique=False)
    op.create_index(op.f('ix_training_plans_start_date'), 'training_plans', ['start_date'], unique=False)
    op.create_index(op.f('ix_training_plans_status'), 'training_plans', ['status'], unique=False)
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='workoutdifficulty'), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('intensity_factor', sa.Float(), nullable=False),
    sa.Column('workout_category', sa.String(length=50), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_global = true AND user_id IS NULL) OR (is_global = false AND user_id IS NOT NULL)', name='ck_workout_global_consistency'),
    sa.CheckConstraint('(min_age IS NULL) OR (max_age IS NULL) OR (min_age <= max_age)', name='ck_workout_age_range'),
    sa.CheckConstraint('days_per_week >= 1 AND days_per_week <= 7', name='ck_workout_days_per_week'),
    sa.CheckConstraint('intensity_factor > 0', name='ck_workout_intensity_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout_active_goal_difficulty', 'workout_templates', ['is_active', 'goal', 'difficulty'], unique=False)
    op.create_index('idx_workout_global_active', 'workout_templates', ['is_global', 'is_active'], unique=False)
    op.create_index(op.f('ix_workout_templates_difficulty'), 'workout_templates', ['difficulty'], unique=False)
    op.create_index(op.f('ix_workout_templates_goal'), 'workout_templates', ['goal'], unique=False)
    op.create_index(op.f('ix_workout_templates_is_active'), 'workout_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_workout_templates_is_global'), 'workout_templates', ['is_global'], unique=False)
    op.create_index(op.f('ix_workout_templates_user_id'), 'workout_templates', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_templates_workout_category'), 'workout_templates', ['workout_category'], unique=False)
    op.create_table('custom_question_scoring_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('answer_value', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(option_id IS NOT NULL) OR (answer_value IS NOT NULL)', name='ck_scoring_weight_has_value'),
    sa.ForeignKeyConstraint(['option_id'], ['custom_question_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'answer_value', name='uq_question_answer_value_weight'),
    sa.UniqueConstraint('question_id', 'option_id', name='uq_question_option_weight')
    )
    op.create_index('idx_scoring_weight_question_answer', 'custom_question_scoring_weights', ['question_id', 'answer_value'], unique=False)
    op.create_index('idx_scoring_weight_question_option', 'custom_question_scoring_weights', ['question_id', 'option_id'], unique=False)
    op.create_index(op.f('ix_custom_question_scoring_weights_answer_value'), 'custom_question_scoring_weights', ['answer_value'], unique=False)
    op.create_index(op.f('ix_custom_question_scoring_weights_option_id'), 'custom_question_scoring_weights', ['option_id'], unique=False)
    op.create_index(op.f('ix_custom_question_scoring_weights_question_id'), 'custom_question_scoring_weights', ['question_id'], unique=False)
    op.create_table('question_template_links',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'template_id')
    )
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('volume_multiplier', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(day_of_week IS NULL) OR (day_of_week >= 0 AND day_of_week <= 6)', name='ck_scheduled_workout_day_of_week'),
    sa.CheckConstraint('(is_completed = false) OR (completed_at IS NOT NULL)', name='ck_scheduled_workout_completed'),
    sa.CheckConstraint('volume_multiplier > 0', name='ck_scheduled_workout_volume_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'scheduled_for', name='uq_scheduled_workout_plan_date')
    )
    op.create_index('idx_scheduled_workout_plan_date', 'scheduled_workouts', ['plan_id', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_is_completed'), 'scheduled_workouts', ['is_completed'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_plan_id'), 'scheduled_workouts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_scheduled_for'), 'scheduled_workouts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_template_id'), 'scheduled_workouts', ['template_id'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(option_id IS NOT NULL) OR (value IS NOT NULL)', name='ck_user_answer_has_value'),
    sa.ForeignKeyConstraint(['option_id'], ['custom_question_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['custom_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', 'option_id', name='uq_user_question_option')
    )
    op.create_index('idx_user_answers_user_id', 'user_answers', ['user_id'], unique=False)
    op.create_index('idx_user_answers_user_question', 'user_answers', ['user_id', 'question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_option_id'), 'user_answers', ['option_id'], unique=False)
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    op.create_index(op.f('ix_workout_exercises_sort_order'), 'workout_exercises', ['sort_order'], unique=False)
    op.create_table('workout_template_equipment',
    sa.Column('workout_template_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_template_id', 'equipment_id')
    )
    op.create_index('idx_wt_equipment_equipment', 'workout_template_equipment', ['equipment_id'], unique=False)
    op.create_index('idx_wt_equipment_template', 'workout_template_equipment', ['workout_template_id'], unique=False)
    op.create_index(op.f('ix_workout_template_equipment_equipment_id'), 'workout_template_equipment', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_workout_template_equipment_workout_template_id'), 'workout_template_equipment', ['workout_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_template_equipment_workout_template_id'), table_name='workout_template_equipment')
    op.drop_index(op.f('ix_workout_template_equipment_equipment_id'), table_name='workout_template_equipment')
    op.drop_index('idx_wt_equipment_template', table_name='workout_template_equipment')
    op.drop_index('idx_wt_equipment_equipment', table_name='workout_template_equipment')
    op.drop_table('workout_template_equipment')
    op.drop_index(op.f('ix_workout_exercises_sort_order'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_option_id'), table_name='user_answers')
    op.drop_index('idx_user_answers_user_question', table_name='user_answers')
    op.drop_index('idx_user_answers_user_id', table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_scheduled_workouts_template_id'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_scheduled_for'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_plan_id'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_is_completed'), table_name='scheduled_workouts')
    op.drop_index('idx_scheduled_workout_plan_date', table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    op.drop_table('question_template_links')
    op.drop_index(op.f('ix_custom_question_scoring_weights_question_id'), table_name='custom_question_scoring_weights')
    op.drop_index(op.f('ix_custom_question_scoring_weights_option_id'), table_name='custom_question_scoring_weights')
    op.drop_index(op.f('ix_custom_question_scoring_weights_answer_value'), table_name='custom_question_scoring_weights')
    op.drop_index('idx_scoring_weight_question_option', table_name='custom_question_scoring_weights')
    op.drop_index('idx_scoring_weight_question_answer', table_name='custom_question_scoring_weights')
    op.drop_table('custom_question_scoring_weights')
    op.drop_index(op.f('ix_workout_templates_workout_category'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_user_id'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_is_global'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_is_active'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_goal'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_difficulty'), table_name='workout_templates')
    op.drop_index('idx_workout_global_active', table_name='workout_templates')
    op.drop_index('idx_workout_active_goal_difficulty', table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_status'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_start_date'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_end_date'), table_name='training_plans')
    op.drop_index('idx_training_plan_user_status', table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index('idx_payment_user_status', table_name='payments')
    op.drop_table('payments')
    op.drop_table('exercise_muscles')
    op.drop_table('exercise_contraindications')
    op.drop_index(op.f('ix_custom_question_options_sort_order'), table_name='custom_question_options')
    op.drop_index(op.f('ix_custom_question_options_question_id'), table_name='custom_question_options')
    op.drop_table('custom_question_options')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_muscles_name'), table_name='muscles')
    op.drop_table('muscles')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_custom_questions_order'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_key'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_is_system'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_is_active'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_category'), table_name='custom_questions')
    op.drop_index(op.f('ix_custom_questions_answer_type'), table_name='custom_questions')
    op.drop_index('idx_custom_question_system_active', table_name='custom_questions')
    op.drop_index('idx_custom_question_active_order', table_name='custom_questions')
    op.drop_table('custom_questions')
    op.drop_index(op.f('ix_contraindications_name'), table_name='contraindications')
    op.drop_table('contraindications')
    op.drop_index(op.f('ix_admin_accounts_username'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###

