"""empty message

Revision ID: 69da7a776931
Revises: 91425a8a2c14
Create Date: 2026-02-02 04:41:07.837534

"""
from alembic import op
import sqlalchemy as sa


revision = '69da7a776931'
down_revision = '91425a8a2c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'CANCELLED', name='trainingplanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('volume_multiplier', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_workouts_plan_id'), 'scheduled_workouts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_scheduled_for'), 'scheduled_workouts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_template_id'), 'scheduled_workouts', ['template_id'], unique=False)
    op.add_column('exercises', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('exercises', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column(
        'exercises',
        sa.Column('muscles', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    )
    op.add_column('exercises', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exercises', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Convert old comma-separated string to JSON array (safe for '' / NULL)
    op.execute(
        """
        ALTER TABLE exercises
        ALTER COLUMN contraindications TYPE json
        USING (
          CASE
            WHEN contraindications IS NULL OR contraindications = '' THEN '[]'::json
            ELSE to_json(string_to_array(contraindications, ','))::json
          END
        )
        """.strip()
    )
    op.add_column(
        'workout_exercises',
        sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column('workout_exercises', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('workout_exercises', sa.Column('reps', sa.Integer(), nullable=True))
    op.add_column('workout_exercises', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('workout_exercises', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    op.add_column('workout_exercises', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('workout_exercises', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workout_exercises', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_workout_exercises_sort_order'), 'workout_exercises', ['sort_order'], unique=False)
    op.drop_constraint(op.f('workout_exercises_workout_id_fkey'), 'workout_exercises', type_='foreignkey')
    op.drop_constraint(op.f('workout_exercises_exercise_id_fkey'), 'workout_exercises', type_='foreignkey')
    op.create_foreign_key(
        "fk_workout_exercises_exercise_id",
        'workout_exercises',
        'exercises',
        ['exercise_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        "fk_workout_exercises_workout_id",
        'workout_exercises',
        'workout_templates',
        ['workout_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column('workout_templates', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column(
        'workout_templates',
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    )
    op.add_column('workout_templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workout_templates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_templates', 'updated_at')
    op.drop_column('workout_templates', 'created_at')
    op.drop_column('workout_templates', 'is_active')
    op.drop_column('workout_templates', 'description')
    op.drop_constraint("fk_workout_exercises_workout_id", 'workout_exercises', type_='foreignkey')
    op.drop_constraint("fk_workout_exercises_exercise_id", 'workout_exercises', type_='foreignkey')
    op.create_foreign_key(op.f('workout_exercises_exercise_id_fkey'), 'workout_exercises', 'exercises', ['exercise_id'], ['id'])
    op.create_foreign_key(op.f('workout_exercises_workout_id_fkey'), 'workout_exercises', 'workout_templates', ['workout_id'], ['id'])
    op.drop_index(op.f('ix_workout_exercises_sort_order'), table_name='workout_exercises')
    op.drop_column('workout_exercises', 'updated_at')
    op.drop_column('workout_exercises', 'created_at')
    op.drop_column('workout_exercises', 'notes')
    op.drop_column('workout_exercises', 'rest_seconds')
    op.drop_column('workout_exercises', 'duration_seconds')
    op.drop_column('workout_exercises', 'reps')
    op.drop_column('workout_exercises', 'sets')
    op.drop_column('workout_exercises', 'sort_order')
    op.execute(
        """
        ALTER TABLE exercises
        ALTER COLUMN contraindications TYPE varchar(512)
        USING (
          CASE
            WHEN contraindications IS NULL THEN ''
            WHEN json_typeof(contraindications) = 'array' THEN (
              SELECT array_to_string(array_agg(value), ',')
              FROM json_array_elements_text(contraindications) AS value
            )
            ELSE ''
          END
        )
        """.strip()
    )
    op.drop_column('exercises', 'updated_at')
    op.drop_column('exercises', 'created_at')
    op.drop_column('exercises', 'muscles')
    op.drop_column('exercises', 'video_url')
    op.drop_column('exercises', 'description')
    op.drop_index(op.f('ix_scheduled_workouts_template_id'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_scheduled_for'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_plan_id'), table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    # ### end Alembic commands ###

