from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self

from src.domain.entities.user import User
from src.domain.entities.user_answer import UserAnswer
from src.domain.entities.exercise import Exercise
from src.domain.entities.workout import WorkoutTemplate
from src.domain.entities.payment import Payment
from src.domain.entities.questionnaire import CustomQuestion


class IUserRepository(Protocol):
    async def get_by_telegram_id(self, tg_id: int) -> User | None: ...
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def list_all(self) -> list[User]: ...
    async def add(self, user: User) -> None: ...


class IUserAnswerRepository(Protocol):
    async def get_answered_keys(self, user_id: int) -> set[str]: ...
    async def list_by_user_id(self, user_id: int) -> list[UserAnswer]: ...
    async def delete_by_question(self, user_id: int, question_id: int) -> None: ...
    async def add_many(self, answers: list[UserAnswer]) -> None: ...


class IExerciseRepository(Protocol):
    async def list_all(self) -> list[Exercise]: ...


class IWorkoutTemplateRepository(Protocol):
    async def list_all(self) -> list[WorkoutTemplate]: ...
    async def add(self, template: WorkoutTemplate) -> None: ...


class IPaymentRepository(Protocol):
    async def add(self, payment: Payment) -> None: ...
    async def get_by_invoice_id(self, invoice_id: str) -> Payment | None: ...


class ICustomQuestionRepository(Protocol):
    async def list_active(self) -> list[CustomQuestion]: ...
    async def list_active_ordered(self) -> list[CustomQuestion]: ...
    async def list_all(self) -> list[CustomQuestion]: ...
    async def get(self, question_id: int) -> CustomQuestion | None: ...
    async def get_by_key(self, key: str) -> CustomQuestion | None: ...
    async def add(self, question: CustomQuestion) -> None: ...


class IQuestionTemplateLinkRepository(Protocol):
    async def add(self, question_id: int, template_id: int) -> None: ...
    async def list_all(self) -> list[tuple[int, int]]: ...


class UnitOfWork(Protocol):
    users: IUserRepository
    exercises: IExerciseRepository
    workouts: IWorkoutTemplateRepository
    payments: IPaymentRepository
    custom_questions: ICustomQuestionRepository
    user_answers: IUserAnswerRepository
    question_template_links: IQuestionTemplateLinkRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

