from __future__ import annotations

from datetime import date
from types import TracebackType
from typing import TYPE_CHECKING, Protocol, Self

if TYPE_CHECKING:
    from src.application.specifications import Specification

from src.domain.entities.admin_account import AdminAccount
from src.domain.entities.user import User
from src.domain.entities.user_answer import UserAnswer
from src.domain.entities.exercise import Exercise
from src.domain.entities.workout import WorkoutTemplate
from src.domain.entities.payment import Payment
from src.domain.entities.questionnaire import CustomQuestion
from src.domain.entities.training_plan import TrainingPlan, ScheduledWorkout
from src.domain.entities.muscle import Muscle
from src.domain.entities.contraindication import Contraindication
from src.domain.entities.equipment import Equipment
from src.domain.entities.base import Base


class IAdminAccountRepository(Protocol):
    async def get_by_username(self, username: str) -> AdminAccount | None: ...
    async def get_by_id(self, account_id: int) -> AdminAccount | None: ...
    async def add(self, account: AdminAccount) -> None: ...
    async def list_all(self) -> list[AdminAccount]: ...
    async def count(self) -> int: ...
    async def count_superusers(self) -> int: ...
    async def delete(self, account_id: int) -> None: ...


class IUserRepository(Protocol):
    async def get_by_telegram_id(self, tg_id: int) -> User | None: ...
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def list_all(self) -> list[User]: ...
    async def add(self, user: User) -> None: ...


class IUserAnswerRepository(Protocol):
    async def get_answered_keys(self, user_id: int) -> set[str]: ...
    async def list_by_user_id(self, user_id: int) -> list[UserAnswer]: ...
    async def delete_by_question(self, user_id: int, question_id: int) -> None: ...
    async def add_many(self, answers: list[UserAnswer]) -> None: ...


class IExerciseRepository(Protocol):
    async def list_all(self) -> list[Exercise]: ...
    async def get_by_id(self, exercise_id: int) -> Exercise | None: ...
    async def get_by_name(self, name: str) -> Exercise | None: ...
    async def add(self, exercise: Exercise) -> None: ...
    async def delete(self, exercise_id: int) -> None: ...


class IMuscleRepository(Protocol):
    async def list_all(self) -> list[Muscle]: ...
    async def get_by_id(self, muscle_id: int) -> Muscle | None: ...
    async def get_by_name(self, name: str) -> Muscle | None: ...
    async def add(self, muscle: Muscle) -> None: ...
    async def delete(self, muscle_id: int) -> None: ...


class IContraindicationRepository(Protocol):
    async def list_all(self) -> list[Contraindication]: ...
    async def get_by_id(self, contraindication_id: int) -> Contraindication | None: ...
    async def get_by_name(self, name: str) -> Contraindication | None: ...
    async def add(self, contraindication: Contraindication) -> None: ...
    async def delete(self, contraindication_id: int) -> None: ...


class IWorkoutTemplateRepository(Protocol):
    async def list_all(self) -> list[WorkoutTemplate]: ...
    async def get_by_id(self, template_id: int) -> WorkoutTemplate | None: ...
    async def add(self, template: WorkoutTemplate) -> None: ...
    async def delete(self, template_id: int) -> None: ...
    async def find_by_specification(self, specification: Specification) -> list[WorkoutTemplate]: ...


class ITrainingPlanRepository(Protocol):
    async def add(self, plan: TrainingPlan) -> None: ...
    async def get_active_for_user(self, user_id: int) -> TrainingPlan | None: ...


class IScheduledWorkoutRepository(Protocol):
    async def add(self, scheduled: ScheduledWorkout) -> None: ...
    async def add_many(self, items: list[ScheduledWorkout]) -> None: ...
    async def get_by_plan_and_date(self, plan_id: int, on_date: date) -> ScheduledWorkout | None: ...
    async def list_by_plan_id(self, plan_id: int) -> list[ScheduledWorkout]: ...
    async def mark_completed(self, scheduled_id: int) -> None: ...


class IPaymentRepository(Protocol):
    async def add(self, payment: Payment) -> None: ...
    async def get_by_invoice_id(self, invoice_id: str) -> Payment | None: ...


class ICustomQuestionRepository(Protocol):
    async def list_active(self) -> list[CustomQuestion]: ...
    async def list_active_ordered(self) -> list[CustomQuestion]: ...
    async def list_all(self) -> list[CustomQuestion]: ...
    async def get(self, question_id: int) -> CustomQuestion | None: ...
    async def get_by_key(self, key: str) -> CustomQuestion | None: ...
    async def add(self, question: CustomQuestion) -> None: ...
    async def get_scoring_weight(self, question_id: int, answer_value: str) -> int | None: ...


class IEquipmentRepository(Protocol):
    async def list_all(self) -> list[Equipment]: ...
    async def list_active(self) -> list[Equipment]: ...
    async def get_by_id(self, equipment_id: int) -> Equipment | None: ...
    async def get_by_name(self, name: str) -> Equipment | None: ...
    async def add(self, equipment: Equipment) -> None: ...
    async def delete(self, equipment_id: int) -> None: ...


# Gender модель удалена - пол хранится как строка в workout_template_allowed_genders


class IQuestionTemplateLinkRepository(Protocol):
    async def add(self, question_id: int, template_id: int) -> None: ...
    async def list_all(self) -> list[tuple[int, int]]: ...


class UnitOfWork(Protocol):
    admin_accounts: IAdminAccountRepository
    users: IUserRepository
    exercises: IExerciseRepository
    muscles: IMuscleRepository
    contraindications: IContraindicationRepository
    workouts: IWorkoutTemplateRepository
    training_plans: ITrainingPlanRepository
    scheduled_workouts: IScheduledWorkoutRepository
    payments: IPaymentRepository
    custom_questions: ICustomQuestionRepository
    user_answers: IUserAnswerRepository
    question_template_links: IQuestionTemplateLinkRepository
    equipment: IEquipmentRepository
    # genders: IGenderRepository  # Удалено - Gender модель больше не используется

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def rollback(self) -> None: ...
    async def refresh(self, entity: Base) -> None: ...

